### PR TITLE
Add k8s support

### PR DESCRIPTION
**Pull request by simonostendorf**
- Adds helm chart to deploy portals
- Remove ansible from previous year
- Adds deploy guideline for cluster and cluster addons
- Adds redis and postgresql cluster deployment
- Add ci to release helm chart

### CODE REVIEW

**Comment by simonostendorf** [comment]
logging, monitoring, redis-cluster usage (see #378), cluster and pod autoscaler and cpu/ram requests are still missing. Because these are tracked in #89 and this PR adds the basic k8s support that is needed, i would mark this PR as ready to merge and create a new PR for the additional k8s tasks.

**Review by TitusKirch — APPROVED** [review]
Untested, but looked over and so far looks quite good

**Comment by simonostendorf** [comment]
> Untested, but looked over and so far looks quite good

I've tested it. The currently running cluster was build using this guide. :)

**Comment by TitusKirch** [comment]
> > Untested, but looked over and so far looks quite good
> 
> I've tested it. The currently running cluster was build using this guide. :)
> 
> Only helm release action is untested.

Yes, I know, I just wanted to say that I have not tested it.

**Pull request merged**
